## mybatis config
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    configuration-properties:
        dialectClass:com.kevin.mybatis.dialect.MySql5Dialect
    type-handlers-package: com.kevin.mybatis.handler
## datasource config
dbconfig:
    db1:
        dbName: db1
        typeAliasesPackage: com.kevin.model.db1
        mapperLocations: classpath*:mybatis/db1/*.xml
    db2:
        dbName: db2
        typeAliasesPackage: com.kevin.model.db2
        mapperLocations: classpath*:mybatis/db2/*.xml


